// Phase 8.1 — BIN -> street address (from the PLUTO-derived map). Pure accessor so
// reviews and UI identify buildings by address, never BIN. Map is generated by
// scripts/derive-bin-addresses.mjs.
import data from "./data/real-data/bin-addresses.v0.1.json" with { type: "json" };

export function addressForBin(bin) {
  return data.addresses[String(bin)] ?? null;
}
